---
language: python
services: docker

install:
  # Install test dependencies.
  - pip install molecule docker

#before_script:
#  - cd ../
#  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
#  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
