---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "rndmh3ro/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/lib/systemd/systemd"}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: inspec
  lint:
    name: rubocop
    enabled: false
